using System.Text;
using Content.Shared._Horizon.Mech;
using Content.Shared.Chemistry.Reagent;
using Content.Shared.Timing;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;

namespace Content.Client._Horizon.Mech.UI;

[GenerateTypedNameReferences]
public sealed partial class MechGunUiFragment : BoxContainer
{
    [Dependency] private readonly IGameTiming _timing = default!;
    [Dependency] private readonly IPrototypeManager _proto = default!;

    public event Action<EntityUid?>? ReloadAction;
    public event Action<string>? SelectReagentAction;

    public EntityUid? FragmentOwner;
    private StartEndTime _reloadTimer;
    public float ReloadTime = 10f;

    public MechGunUiFragment()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        var curTime = _timing.CurTime;

        var progress = _reloadTimer.ProgressAt(curTime);

        ReloadButton.OnPressed += _ => ReloadAction?.Invoke(FragmentOwner);

        if (progress >= 1 && ReloadButton.Disabled)
            ReloadButton.Disabled = false;
    }

    public void UpdateContents(MechGunUiState state)
    {
        ReloadTime = state.ReloadTime;

        if (state.Reloading && state.ReloadEndTime != null)
        {
            _reloadTimer.End = state.ReloadEndTime.Value;
            _reloadTimer.Start = state.ReloadEndTime.Value - TimeSpan.FromSeconds(ReloadTime);
            ReloadButton.Disabled = true;
        }
        else
        {
            ShotsCount.Text = $"{state.Shots} / {state.Capacity}";
        }

        ReagentSelect.Clear();

        if (state.AllowedReagents.Count == 0)
        {
            ReagentContainer.Visible = false;
            return;
        }
        else
        {
            ReagentContainer.Visible = true;

            for (var i = 0; i < state.AllowedReagents.Count; i++)
            {
                var reagent = _proto.Index<ReagentPrototype>(state.AllowedReagents[i]);

                var reagentName = new StringBuilder(reagent.LocalizedName);
                reagentName[0] = char.ToUpper(reagentName[0]);

                ReagentSelect.AddItem(reagentName.ToString(), i);

                if (reagent.ID == state.SelectedReagent)
                    ReagentSelect.SelectId(i);
            }

            ReagentSelect.OnItemSelected += args =>
            {
                var selectedReagent = state.AllowedReagents[args.Id];
                SelectReagentAction?.Invoke(selectedReagent);
                ReagentSelect.SelectId(args.Id);
            };
        }
    }

    public void StartTimer()
    {
        var curTime = _timing.CurTime;
        _reloadTimer.Start = curTime;
        _reloadTimer.End = curTime + TimeSpan.FromSeconds(ReloadTime);
        ReloadButton.Disabled = true;
    }
}
