using System.Linq;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Horizon.Mech.UI;

[GenerateTypedNameReferences]
public sealed partial class MechToolsUiFragment : BoxContainer
{
    public event Action<string>? SelectAction;
    private List<string> _tools = new();

    public MechToolsUiFragment()
    {
        RobustXamlLoader.Load(this);
    }

    public void Startup(List<string?> tools, string current, IEntityManager entMan)
    {
        if (_tools.SequenceEqual(tools))
            return;

        ToolsContainer.RemoveAllChildren();
        ButtonGroup group = new(false);

        foreach (var item in tools)
        {
            if (item == null)
                continue;

            var ent = entMan.Spawn(item);

            var panel = new PanelContainer()
            {
                SetSize = new(48),
                Margin = new Thickness(2, 0, 2, 0),
                PanelOverride = new StyleBoxFlat() { BackgroundColor = Color.Black }
            };

            var sprite = new SpriteView()
            {
                VerticalAlignment = VAlignment.Center,
                HorizontalAlignment = HAlignment.Center,
                Scale = new(2, 2)
            };

            sprite.SetEntity(ent);

            var button = new Button()
            {
                ToggleMode = true,
                Group = group,
                SetSize = new(64),
                Margin = new Thickness(2, 0, 2, 0),
                Children = { panel, sprite }
            };

            button.OnPressed += _ => SelectAction?.Invoke(item);

            ToolsContainer.AddChild(button);
        }
    }

    public void UpdateSelected(string current, IEntityManager entMan)
    {
        foreach (var item in ToolsContainer.Children)
        {
            if (item is not Button button || button.Group == null)
                continue;

            var sprite = button.Children.OfType<SpriteView>().FirstOrDefault();
            if (sprite == null || sprite.Entity == null)
                continue;

            var protoId = entMan.GetComponent<MetaDataComponent>(sprite.Entity.Value).EntityPrototype?.ID;
            if (protoId == null)
                continue;

            button.Pressed = protoId == current;
            break;
        }
    }
}
