using Content.Client.Message;
using Content.Client.UserInterface.Controls;
using Content.Shared._Horizon.FlavorText;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Horizon.FlavorText.UI;

[GenerateTypedNameReferences]
public sealed partial class FlavorTextMenu : FancyWindow
{
    public FlavorTextMenu()
    {
        RobustXamlLoader.Load(this);
        BottomCloseButton.OnPressed += args => Close();

        TabContainer.SetTabTitle(0, Loc.GetString("flavor-menu-tab-ic"));
        TabContainer.SetTabTitle(1, Loc.GetString("flavor-menu-tab-ooc"));
    }

    public void Populate(EntityUid? ent, string name, string icDesc, string oocDesc, ErpStatus erp)
    {
        IcSprite.SetEntity(ent);
        OocSprite.SetEntity(ent);

        IcNameLabel.SetMarkup(name);
        OocNameLabel.SetMarkup(name);

        ICDescriptionLabel.SetMarkup(icDesc != string.Empty ? icDesc : Loc.GetString("flavor-no-ic-desc"));
        OOCDescriptionLabel.SetMarkup(oocDesc != string.Empty ? oocDesc : Loc.GetString("flavor-no-ooc-desc"));
        ErpStatusLabel.SetMarkup(Loc.GetString($"erp-status-{erp}-flavor"));
    }
}
