using Content.Client.Message;
using Content.Shared.Hands.Components;
using Content.Shared.Traits;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client._Horizon.Traits;

[GenerateTypedNameReferences]
public sealed partial class FancyTraitPreferenceSelector : Control
{
    public int Cost;

    public bool Preference
    {
        get => Checkbox.Pressed;
        set => Checkbox.Pressed = value;
    }

    public event Action<bool>? PreferenceChanged;

    private string _nameString = "";

    public FancyTraitPreferenceSelector(TraitPrototype trait)
    {
        RobustXamlLoader.Load(this);

        _nameString = $"{Loc.GetString(trait.Name)} {(trait.Cost != 0 ? $"[bold]-{trait.Cost}[/bold] " : "")}";

        Cost = trait.Cost;
        NameLabel.SetMarkup(_nameString);
        Checkbox.OnToggled += OnCheckBoxToggled;

        if (trait.Description is { } desc)
        {
            Checkbox.ToolTip = Loc.GetString(desc);
        }
    }

    private void OnCheckBoxToggled(BaseButton.ButtonToggledEventArgs args)
    {
        PreferenceChanged?.Invoke(Preference);
    }

    public void UpdateName(bool locked)
    {
        NameLabel.SetMarkup($"[color={((locked && !Checkbox.Pressed) ? "crimson" : "white")}]{_nameString}[/color]");
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        BackgroundPanel.ModulateSelfOverride = Checkbox.IsHovered ? null : Color.Transparent;
    }
}
