using Content.Client.Lobby.UI;
using Content.Client.Message;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Horizon.Traits;

[GenerateTypedNameReferences]
public sealed partial class QuirkEntry : Control
{
    public Action<bool>? OnTraitToggled;
    public string ProtoId;

    public QuirkEntry(string id, string name, string description, int cost, HumanoidProfileEditor.QuirkColoration category, bool isSelected, string? denyReason)
    {
        RobustXamlLoader.Load(this);

        ProtoId = id;

        var color = category switch
        {
            HumanoidProfileEditor.QuirkColoration.Positive => Color.LimeGreen,
            HumanoidProfileEditor.QuirkColoration.Negative => Color.Crimson,
            HumanoidProfileEditor.QuirkColoration.Neutral => Color.LightGray
        };

        var costSymbol = cost switch
        {
            > 0 => "+",
            _ => ""
        };

        ToggleQuirkButton.ToolTip = denyReason;

        ToggleQuirkButton.Disabled = denyReason != null;
        ToggleQuirkButton.Pressed = isSelected;
        ToggleQuirkButton.OnToggled += arg => OnTraitToggled?.Invoke(arg.Pressed);

        QuirkNameLabel.SetMarkup($"{Loc.GetString(name)} [color={color.ToHex()}]{costSymbol}{Loc.GetString("humanoid-profile-editor-quirks-cost", ("cost", cost))}[/color]");
        QuirkDescLabel.SetMarkup(Loc.GetString(description));
    }

    public void UpdateEntry(bool isSelected, bool canApply)
    {
        if (!canApply)
        {
            ToggleQuirkButton.ToolTip = isSelected ? Loc.GetString("humanoid-profile-editor-quirks-cannot-remove") :
                                                     Loc.GetString("humanoid-profile-editor-quirks-cannot-add");
        }
        else
        {
            ToggleQuirkButton.ToolTip = null;
        }

        ToggleQuirkButton.Disabled = !canApply;
        ToggleQuirkButton.Pressed = isSelected;
    }
}
