using Content.Client.Lobby.UI;
using Content.Client.Message;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Horizon.Traits;

[GenerateTypedNameReferences]
public sealed partial class QuirkEntry : Control
{
    public Action<bool>? OnTraitToggled;
    public QuirkEntry(string name, string description, int cost, HumanoidProfileEditor.QuirkCategory category, bool isSelected, bool canApply)
    {
        RobustXamlLoader.Load(this);

        var color = category switch
        {
            HumanoidProfileEditor.QuirkCategory.Positive => Color.LimeGreen,
            HumanoidProfileEditor.QuirkCategory.Negative => Color.Crimson,
            HumanoidProfileEditor.QuirkCategory.Neutral => Color.LightGray
        };

        var costSymbol = cost switch
        {
            > 0 => "+",
            _ => ""
        };

        if (!canApply)
            ToggleQuirkButton.ToolTip = isSelected ? Loc.GetString("humanoid-profile-editor-quirks-cannot-remove") : Loc.GetString("humanoid-profile-editor-quirks-cannot-add");

        ToggleQuirkButton.Disabled = !canApply;
        ToggleQuirkButton.Pressed = isSelected;
        ToggleQuirkButton.OnToggled += arg => OnTraitToggled?.Invoke(arg.Pressed);

        QuirkNameLabel.SetMarkup($"{Loc.GetString(name)} [color={color.ToHex()}]{costSymbol}{Loc.GetString("humanoid-profile-editor-quirks-cost", ("cost", cost))}[/color]");
        QuirkDescLabel.SetMarkup(Loc.GetString(description));
    }
}
