using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Content.Shared._Horizon.AnCoDisposableFabricator;
using Robust.Client.GameObjects;

namespace Content.Client._Horizon.AnCoDisposableFabricator;

[GenerateTypedNameReferences]
public sealed partial class AnCoDisposableFabricatorSet : Control
{
    public AnCoDisposableFabricatorSet(AnCoDisposableFabricatorSetInfo set, SpriteSystem spriteSystem)
    {
        RobustXamlLoader.Load(this);

        Icon.Texture = spriteSystem.Frame0(set.Sprite);
        SetName.Text = Loc.GetString(set.Name);
        SetDescription.Text = Loc.GetString(set.Description);
        SetButton.Text = Loc.GetString(set.Selected ? "anco-disposable-fabricator-button-deselect" : "anco-disposable-fabricator-button-select");
        SetButton.ModulateSelfOverride = set.Selected ? new Color(240, 90, 90) : new Color(98, 5, 5);
    }
}
