using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Horizon.OutpostCaptureUI;

[GenerateTypedNameReferences]
public sealed partial class OutpostCaptureWindow : DefaultWindow
{
    public OutpostCaptureWindow()
    {
        RobustXamlLoader.Load(this);
    }
}

