using Content.Client.Message;
using Content.Shared._Horizon.Expeditions;
using Content.Shared.IdentityManagement;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Horizon.Expeditions.Ui;

[GenerateTypedNameReferences]
public sealed partial class ExpeditionGoalOption : PanelContainer
{
    public event Action? ClaimPressed;

    public ExpeditionGoalOption(int idx, ExpeditionGoal goal, IEntityManager entMan)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        TitleStripe.Text = Loc.GetString("expeditions-goal-title-label", ("id", idx));

        DescriptionLabel.SetMarkup(goal.Description);
        RequiredAmountLabel.SetMarkup(Loc.GetString("expeditions-goal-required-amount-label", ("amount", goal.RequiredAmount)));
        RewardLabel.SetMarkup(Loc.GetString("expeditions-goal-reward-label", ("reward", goal.Reward), ("currency", goal.CurrencyStr)));
        Icon.SetEntity(entMan.Spawn(goal.IconEntity));

        // Если есть доп награда, показываем текст с ней
        if (goal.RewardEntity != null)
        {
            var ent = entMan.Spawn(goal.RewardEntity);
            AdditionalRewardLabel.Visible = true;
            AdditionalRewardLabel.SetMarkup(Loc.GetString("expeditions-goal-reward-entity-label", ("entity", Identity.Name(ent, entMan))));

            entMan.QueueDeleteEntity(ent);
        }

        LayoutContainer.SetAnchorPreset(this, LayoutContainer.LayoutPreset.Wide);
        BigPanel.ModulateSelfOverride = new Color(30, 30, 34);

        ClaimButton.OnPressed += args => ClaimPressed?.Invoke();
    }
}
