using System.Linq;
using Content.Client.Computer;
using Content.Client.UserInterface.Controls;
using Content.Shared._Horizon.Expeditions;
using Content.Shared.Shuttles.BUIStates;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;

namespace Content.Client._Horizon.Expeditions.Ui;

[GenerateTypedNameReferences]
public sealed partial class ExpeditionGoalsConsoleMenu : FancyWindow,
    IComputerWindow<EmergencyConsoleBoundUserInterfaceState>
{
    [Dependency] private readonly IEntityManager _entMan = default!;
    [Dependency] private readonly IGameTiming _timing = default!;

    public TimeSpan NextOffer;
    public TimeSpan Cooldown = TimeSpan.FromMinutes(5);

    public ProtoId<ExpeditionGoalCategoryPrototype> CurrentSpecification = "Crew";
    public Dictionary<ProtoId<ExpeditionGoalCategoryPrototype>, Dictionary<int, ExpeditionGoal>> CachedGoals = new();

    public Action<int>? OnOptionSelected;
    private Action<int>? _specificationSelect;

    public ExpeditionGoalsConsoleMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        SpecificationButton.OnItemSelected += args =>
        {
            _specificationSelect?.Invoke(args.Id);
        };
    }

    /// <summary>
    /// Обновляет меню
    /// </summary>
    public void Populate()
    {
        Container.DisposeAllChildren();

        if (!CachedGoals.TryGetValue(CurrentSpecification, out var options))
            return;

        foreach (var option in options)
        {
            var optionControl = new ExpeditionGoalOption(option.Key, option.Value, _entMan);
            optionControl.ClaimPressed += () => OnOptionSelected?.Invoke(option.Key);
            Container.AddChild(optionControl);
        }
    }

    /// <summary>
    /// Обновляет доступные категории
    /// </summary>
    /// <param name="specifications"></param>
    public void UpdateSpecifications(List<ProtoId<ExpeditionGoalCategoryPrototype>> specifications)
    {
        SpecificationButton.Clear();

        for (var i = 0; i < specifications.Count; i++)
        {
            SpecificationButton.AddItem(Loc.GetString($"goal-specification-{specifications[i]}"), i);
        }

        _specificationSelect = args =>
        {
            CurrentSpecification = specifications[args];
            SpecificationButton.Select(args);
            Populate();
        };

        CurrentSpecification = specifications.First();
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        var remaining = NextOffer - _timing.CurTime;

        if (remaining < TimeSpan.Zero)
        {
            NextOfferBar.Value = 1f;
            NextOfferText.Text = "00:00";
        }
        else
        {
            NextOfferBar.Value = 1f - (float)(remaining / Cooldown);
            NextOfferText.Text = $"{remaining.Minutes:00}:{remaining.Seconds:00}";
        }
    }
}
