using System.Linq;
using Content.Shared._Horizon.Expeditions;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Horizon.Expeditions.Ui;

[GenerateTypedNameReferences]
public sealed partial class GoalsListUiFragment : PanelContainer
{
    public event Action<int>? RemovePressed;

    public GoalsListUiFragment()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    public void Populate(Dictionary<int, ExpeditionGoal> goals, IEntityManager entMan)
    {
        Goals.RemoveAllChildren();

        for (var i = 0; i < 2; i++)
        {
            if (goals.Count > i)
            {
                var item = goals.ElementAt(i);
                var option = new ExpeditionGoalOption(item.Key, item.Value, entMan);
                option.ClaimButton.Text = Loc.GetString("expedition-goal-remove-button");
                option.Icon.Scale = new(4, 4);

                option.DescriptionLabel.MaxWidth = 196;

                option.ClaimPressed += () => RemovePressed?.Invoke(item.Key);
                Goals.AddChild(option);
            }
            else
            {
                // Если цели нет, оставляем плесхолдер
                Goals.AddChild(new PanelContainer()
                {
                    VerticalExpand = true,
                    HorizontalExpand = true,
                    Margin = new(4),
                    StyleClasses = { "PdaBorderRect" },
                    Children = { new RichTextLabel() { Text = Loc.GetString("expedition-goal-not-assigned"), HorizontalAlignment = HAlignment.Center } }
                });
            }
        }

        foreach (var item in goals)
        {
        }
    }
}
