using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Content.Shared._Horizon.Cytology.Systems;
using Robust.Client.UserInterface;
using Content.Shared.Chemistry.Reagent;

namespace Content.Client._Horizon.Cytology.Microscope.UI;

[GenerateTypedNameReferences]
public sealed partial class CellSampleItemsControl : Control
{
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;
    public CellSampleItemsControl(CellSampleInfo info)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        DisplayName.Text = info.DisplayName;
        GrowthRateInSeconds.Text = info.GrowthRateInSeconds.ToString();
        ViralSusceptibility.Text = info.ViralSusceptibility.ToString();

        RequiredChemicals.Text = string.Join(" ", GetLocalizedNames(info.RequiredChemicals));
        SupplementaryChemicals.Text = string.Join(" ", GetLocalizedNames(info.SupplementaryChemicals));
        SuppressiveChemicals.Text = string.Join(" ", GetLocalizedNames(info.SuppressiveChemicals));
    }


    private IEnumerable<string> GetLocalizedNames(List<ProtoId<ReagentPrototype>> protoIds)
    {
        foreach (var protoId in protoIds)
        {
            if (_prototypeManager.TryIndex<ReagentPrototype>(protoId, out var proto))
                yield return proto.LocalizedName;
            else
                yield return Loc.GetString("chem-master-window-unknown-reagent-text");
        }
    }
}
