using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Content.Shared._Horizon.Cytology.Systems;

namespace Content.Client._Horizon.Cytology.Microscope.UI;

[GenerateTypedNameReferences]
public sealed partial class MicroscopeWindow : FancyWindow
{
    public MicroscopeWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    public void UpdateState(MicroscopeBoundUserInterfaceState state)
    {

        CellSamplesList.DisposeAllChildren();

        if (state.CellSampleInfo == null || state.CellSampleInfo.Count == 0)
            return;

        foreach (var info in state.CellSampleInfo)
        {
            var item = new CellSampleItemsControl(info);
            CellSamplesList.AddChild(item);
        }
    }

}
