using Content.Shared._Horizon.Language;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Horizon.Languages.UI;

[GenerateTypedNameReferences]
public sealed partial class LanguageEntry : Control
{
    public Action<string>? OnLanguageSelected;
    public string Language = "";

    public LanguageEntry()
    {
        RobustXamlLoader.Load(this);
    }

    public void Populate(LanguagePrototype proto, bool translator)
    {
        Name.Text = proto.LocalizedName;
        if (proto.UiColor.HasValue)
            Name.FontColorOverride = proto.UiColor.Value;
        SelectButton.ToolTip = translator ?
            Loc.GetString("language-choose-button-tooltip-translator") :
            Loc.GetString("language-choose-button-tooltip-known");
        Description.SetMessage(proto.LocalizedDescription);
        Language = proto.ID;

        SelectButton.OnPressed += _ => OnLanguageSelected?.Invoke(proto.ID);
    }
}
