using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._Horizon.Cytology.Console.UI.Items;

[GenerateTypedNameReferences]
public sealed partial class DiskItem : Button
{
    public string DiskPrototypeId;
    public int? DiskId = null;

    private bool _selected;

    public bool Selected
    {
        get => _selected;
        set
        {
            _selected = value;
            if (_selected)
            {
                AddStyleClass("OptionButtonSelected");
            }
            else
            {
                RemoveStyleClass("OptionButtonSelected");
            }
        }
    }

    public DiskItem(string diskPrototypeId, string name, string desc, bool selected, Texture? diskTexture = null)
    {
        RobustXamlLoader.Load(this);

        DiskPrototypeId = diskPrototypeId;
        _selected = selected;

        var msg = new FormattedMessage();
        msg.AddText(desc);

        DiskIcon.Texture = diskTexture;
        DiskName.Text = name;
        DiskDesc.SetMessage(msg);
    }
}

