using Content.Shared._Horizon.Cytology.Components;
using Content.Shared._Horizon.Cytology.Systems;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using System;

namespace Content.Client._Horizon.Cytology.Console.UI.Items;

[GenerateTypedNameReferences]
public sealed partial class SampleItem : Button
{
    public int SampleIndex { get; }

    public event Action<int>? OnDeletePressed;

    private bool _selected;

    public bool Selected
    {
        get => _selected;
        set
        {
            _selected = value;
        }
    }

    public SampleItem(CellSample sample, string name, int index)
    {
        RobustXamlLoader.Load(this);

        SampleIndex = index;

        SampleName.Text = name;
        Progress.Text = Loc.GetString("cytology-console-progress", ("progress", sample.GrowProgress.ToString("P1")));

        CloseButton.OnPressed += args =>
        {
            args.Event.Handle();
            OnDeletePressed?.Invoke(SampleIndex);
        };

    }
}

