using System.Linq;
using Content.Client.Administration.UI.CustomControls;
using Content.Client.Guidebook;
using Content.Client.Lobby;
using Content.Client.Stylesheets;
using Content.Client.UserInterface.Controls;
using Content.Shared.Humanoid;
using Content.Shared.Humanoid.Prototypes;
using Content.Shared.Preferences;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.ContentPack;
using Robust.Shared.Prototypes;

namespace Content.Client._Horizon.Lobby.UI;

[GenerateTypedNameReferences]
public sealed partial class SpeciesWindow : FancyWindow
{
    public event Action<ProtoId<SpeciesPrototype>>? ChooseAction;
    public ProtoId<SpeciesPrototype> CurrentSpecies;

    public HumanoidCharacterProfile Profile;
    private readonly IPrototypeManager _proto;
    private readonly LobbyUIController _uIController;
    private readonly IResourceManager _resMan;
    [Dependency] private readonly DocumentParsingManager _parsingMan = default!;

    public SpeciesWindow(HumanoidCharacterProfile profile,
                        IPrototypeManager proto,
                        LobbyUIController uIController,
                        IResourceManager resManager)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        Profile = profile;
        _proto = proto;
        _uIController = uIController;
        _resMan = resManager;

        Select.OnPressed += args => ChooseAction?.Invoke(CurrentSpecies);

        var protoList = _proto.EnumeratePrototypes<SpeciesPrototype>().Where(x => x.RoundStart).ToList();
        protoList.OrderBy(x => Loc.GetString(x.Name));

        foreach (var item in protoList)
        {
            var button = new SpeciesButton(item)
            {
                HorizontalExpand = true,
                ToggleMode = true,
                Pressed = Profile.Species == item.ID,
                Text = Loc.GetString(item.Name),
                Margin = new Thickness(5f, 5f),
            };
            button.OnToggled += args => SelectSpecies(item.ID);
            SpeciesContainer.AddChild(button);
        }

        CurrentSpecies = Profile.Species;
        SelectSpecies(Profile.Species);
    }

    public void SelectSpecies(ProtoId<SpeciesPrototype> protoId)
    {
        DetailInfoContainer.DisposeAllChildren();

        foreach (var item in SpeciesContainer.Children)
        {
            if (item is not SpeciesButton button)
                continue;

            button.Pressed = protoId == button.Proto;
        }

        var proto = _proto.Index(protoId);
        var job = Profile.JobPriorities.Where(x => x.Value == JobPriority.High).First().Key;
        CurrentSpecies = protoId;

        var previewProfile = Profile;
        previewProfile = previewProfile.WithSpecies(protoId);

        // Максимально как можем копируем цвет кожи на новую расу
        var skin = proto.SkinColoration;
        switch (skin)
        {
            case HumanoidSkinColor.HumanToned:
                {
                    var tone = SkinColor.HumanSkinToneFromColor(Profile.Appearance.SkinColor);
                    var color = SkinColor.HumanSkinTone((int)tone);

                    previewProfile = previewProfile.WithCharacterAppearance(previewProfile.Appearance.WithSkinColor(color));//
                    break;
                }
            case HumanoidSkinColor.Hues:
                {
                    break;
                }
            case HumanoidSkinColor.TintedHues:
                {
                    var color = SkinColor.TintedHues(Profile.Appearance.SkinColor);

                    previewProfile = previewProfile.WithCharacterAppearance(previewProfile.Appearance.WithSkinColor(color));
                    break;
                }
            case HumanoidSkinColor.VoxFeathers:
                {
                    var color = SkinColor.ClosestVoxColor(Profile.Appearance.SkinColor);

                    previewProfile = previewProfile.WithCharacterAppearance(previewProfile.Appearance.WithSkinColor(color));
                    break;
                }
        }

        var mob = _uIController.LoadProfileEntity(previewProfile, _proto.Index(job), false);  // Раздетый моб
        Mob.SetEntity(mob);

        var loadoutMob = _uIController.LoadProfileEntity(previewProfile, _proto.Index(job), true);    // Моб в одежде должности
        JobLoadout.SetEntity(loadoutMob);

        Select.Disabled = Profile.Species == protoId;

        // Тут у нас идёт штука для создание контейнера плюсов и минусов. Я не уверен, зачем я впихнул это сюда, но мне уже лень переделывать
        var prosConsContainer = new BoxContainer()
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            Margin = new Thickness(5f, 5f),
            MaxWidth = 380f,
        };
        var prosConsLabel = new RichTextLabel()
        {
            Text = Loc.GetString("ui-species-pros-cons"),
            StyleClasses = { StyleBase.ClassLowDivider },
            Margin = new(2f, 2f),
        };
        var separator = new HSeparator()
        {
            Margin = new(2f, 2f, 2f, 4f),
        };
        prosConsContainer.AddChild(prosConsLabel);
        prosConsContainer.AddChild(separator);
        DetailInfoContainer.AddChild(prosConsContainer);

        if (proto.ProsCount <= 0 && proto.SpecialCount <= 0 && proto.ConsCount <= 0)
        {
            // Если нет особенностей, так и пишем
            var noProsConsLabel = new RichTextLabel()
            {
                Text = Loc.GetString("ui-species-no-pros-cons"),
                Margin = new(4f),
                HorizontalAlignment = HAlignment.Center
            };
            DetailInfoContainer.AddChild(noProsConsLabel);
        }
        else
        {
            // Добавляем плюсы и минусы из локали
            for (var i = 0; i < proto.ProsCount; i++)
            {
                var item = $"pros-{proto.ID}-{i + 1}";

                var label = new RichTextLabel()
                {
                    Text = $"[color=#13f244]- {Loc.GetString(item)}[/color]",
                    StyleClasses = { StyleBase.ClassLowDivider },
                    Margin = new(4f, 2f),
                };
                prosConsContainer.AddChild(label);
            }
            prosConsContainer.AddChild(new Control() { MinHeight = 8f });

            for (var i = 0; i < proto.SpecialCount; i++)
            {
                var item = $"special-{proto.ID}-{i + 1}";

                var label = new RichTextLabel()
                {
                    Text = $"[color=#7d7d7d]- {Loc.GetString(item)}[/color]",
                    StyleClasses = { StyleBase.ClassLowDivider },
                    Margin = new(4f, 2f),
                };
                prosConsContainer.AddChild(label);
            }
            prosConsContainer.AddChild(new Control() { MinHeight = 8f });

            for (var i = 0; i < proto.ConsCount; i++)
            {
                var item = $"cons-{proto.ID}-{i + 1}";

                var label = new RichTextLabel()
                {
                    Text = $"[color=#bd0023]- {Loc.GetString(item)}[/color]",
                    StyleClasses = { StyleBase.ClassLowDivider },
                    Margin = new(4f, 2f),
                };
                prosConsContainer.AddChild(label);
            }
            prosConsContainer.AddChild(new Control() { MinHeight = 8f });

        }

        // Проверяем, есть ли описание у расы
        if (!proto.Description.HasValue)
            return;

        // Описания рас берут текст из .xml файлов, поэтому нам нужно найти и использовать контент из указанного файла.
        // По сути, всё работает так же, как и в гайдбуке (и да, сюда можно вставлять изображения)
        using var file = _resMan.ContentFileReadText(proto.Description.Value);
        _parsingMan.TryAddMarkup(DetailInfoContainer, file.ReadToEnd());
    }

    private sealed partial class SpeciesButton(ProtoId<SpeciesPrototype> proto) : Button
    {
        public ProtoId<SpeciesPrototype> Proto = proto;
    }
}
