using System.Numerics;
using Content.Shared._Horizon.GhostSprites;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Serialization.TypeSerializers.Implementations;
using Robust.Shared.Utility;

namespace Content.Client._Horizon.GhostSprites.UI;

[GenerateTypedNameReferences]
public sealed partial class GhostSpriteWindow : DefaultWindow
{
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;
    [Dependency] private readonly IResourceCache _resourceCache = default!;

    public event Action<ProtoId<GhostSpritePrototype>>? OnSpriteSelected;

    private ProtoId<GhostSpritePrototype>? _currentSelection;

    public GhostSpriteWindow()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);
    }

    public void Populate(List<ProtoId<GhostSpritePrototype>> sprites)
    {
        SpriteGrid.DisposeAllChildren();

        foreach (var spriteId in sprites)
        {
            if (!_prototypeManager.TryIndex(spriteId, out var prototype))
                continue;

            var container = CreateSpriteButton(spriteId, prototype);
            SpriteGrid.AddChild(container);
        }
    }

    private BoxContainer CreateSpriteButton(ProtoId<GhostSpritePrototype> spriteId, GhostSpritePrototype prototype)
    {
        var container = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            HorizontalAlignment = HAlignment.Center,
            MinSize = new Vector2(100, 120),
            Margin = new Thickness(4)
        };

        // Create sprite preview
        var spriteView = new TextureRect
        {
            MinSize = new Vector2(64, 64),
            HorizontalAlignment = HAlignment.Center,
            Stretch = TextureRect.StretchMode.KeepAspectCentered
        };

        // Try to load the sprite preview
        var rsiPath = SpriteSpecifierSerializer.TextureRoot / prototype.RsiPath;
        if (_resourceCache.TryGetResource<RSIResource>(rsiPath, out var rsiResource) && rsiResource.RSI != null)
        {
            if (rsiResource.RSI.TryGetState(prototype.State, out var state))
            {
                spriteView.Texture = state.Frame0;
            }
        }

        container.AddChild(spriteView);

        // Create name label
        var nameLabel = new Label
        {
            Text = prototype.Name,
            HorizontalAlignment = HAlignment.Center,
            Margin = new Thickness(0, 4, 0, 0)
        };
        container.AddChild(nameLabel);

        // Create select button
        var selectButton = new Button
        {
            Text = Loc.GetString("ghost-sprite-window-select-button"),
            HorizontalAlignment = HAlignment.Center,
            Margin = new Thickness(0, 4, 0, 0)
        };
        selectButton.OnPressed += _ =>
        {
            _currentSelection = spriteId;
            OnSpriteSelected?.Invoke(spriteId);
        };
        container.AddChild(selectButton);

        return container;
    }

    public void SetCurrentSelection(ProtoId<GhostSpritePrototype>? spriteId)
    {
        _currentSelection = spriteId;
    }
}
