using Content.Client.Humanoid;
using Content.Client.UserInterface.Controls;
using Content.Shared._Horizon.Cytology.Components;
using Content.Shared._Horizon.Cytology.Systems;
using Content.Shared.Preferences;
using Robust.Client.AutoGenerated;
using Robust.Shared.Prototypes;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Map;
using System.Numerics;
using Content.Client._Horizon.Cytology.Console.UI.Items;

namespace Content.Client._Horizon.Cytology.Console.UI;

[GenerateTypedNameReferences]
public sealed partial class CytologySampleCombinatorWindow : FancyWindow
{
    [Dependency] private readonly IEntityManager _entityManager = default!;
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;

    // Child editors
    private ProfileEditor? _profileEditor;
    private ParametersEditor? _parametersEditor;
    private DiskParameters? _diskParameters;

    // State
    private int? _selectedSampleIndex;
    private EntityUid? _previewDummy;
    private SpriteView? _spriteView;
    private BoxContainer? _diskModifiersContainer;

    // Events forwarded to BUI
    public event Action<int, HumanoidCharacterProfile?, List<string>>? OnSaveAll;
    public event Action<int, HumanoidCharacterProfile?>? OnProfileChanged;
    public event Action<int>? OnSampleDelete;

    public CytologySampleCombinatorWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        SaveButton.OnPressed += OnSavePressed;
    }

    /// <summary>
    /// Triggered when the user clicks the "Save Profile" button
    /// Gathers data from both the ProfileEditor and ParametersEditor and invokes the save event
    /// </summary>
    private void OnSavePressed(BaseButton.ButtonEventArgs args)
    {
        if (_selectedSampleIndex is not { } index ||
            _profileEditor == null ||
            _parametersEditor == null)
            return;

        var profile = _profileEditor.Profile;
        var disks = _parametersEditor.SelectedDisks;

        OnSaveAll?.Invoke(index, profile, disks);
    }

    /// <summary>
    /// Updates the entire UI based on the state received from the server
    /// Rebuilds the list of samples and refreshes the currently selected sample's view
    /// </summary>
    public void UpdateState(CytologySampleCombinatorBoundUserInterfaceState state)
    {
        var previousSelection = _selectedSampleIndex;

        CellSamplesList.DisposeAllChildren();

        if (state.CellSamples == null || state.CellSamples.Count == 0)
        {
            _selectedSampleIndex = null;
            ClearPreview();
            ProfileEditorContainer.Visible = false;
            ParametersEditorContainer.Visible = false;
            return;
        }

        for (var i = 0; i < state.CellSamples.Count; i++)
        {
            var index = i;
            var sample = state.CellSamples[index];
            var name = state.CellSamplesNames?[index] ?? "Unknown";

            var item = new SampleItem(sample, name, index);
            item.OnPressed += _ => SelectSample(index, sample, state);

            item.OnDeletePressed += sampleIdx => OnSampleDelete?.Invoke(sampleIdx); // idx можно заменить на index

            CellSamplesList.AddChild(item);

            // Restore selection if the list was refreshed
            if (previousSelection == index)
            {
                // If we are still looking at the same sample, update its data in real-time
                item.Selected = true;
                if (_selectedSampleIndex == index)
                {
                    SelectSample(index, sample, state);
                }
            }
        }

        ProfileButton.OnPressed += _ => ShowProfileEditor();
        ParametersButton.OnPressed += _ => ShowParametersEditor();
    }

    /// <summary>
    /// Selects a specific sample, initializing or updating the editors for it
    /// </summary>
    private void SelectSample(int index, CellSample sample, CytologySampleCombinatorBoundUserInterfaceState state)
    {
        _selectedSampleIndex = index;

        foreach (var child in CellSamplesList.Children)
        {
            if (child is SampleItem button)
                button.Selected = button.SampleIndex == index;
        }

        // Visual feedback for list selection
        if (_profileEditor == null)
        {
            _profileEditor = new ProfileEditor(sample);
            _profileEditor.OnPreviewChanged += profile => UpdatePreview(profile);

            _profileEditor.OnProfileChanged += profile => OnProfileChanged?.Invoke(index, profile);

            ProfileEditorContainer.AddChild(_profileEditor);
        }
        else
        {
            _profileEditor.UpdateSample(sample);
        }

        // Initialize or Update Parameters Editor (Disk selection)
        if (_parametersEditor == null || _diskParameters == null)
        {
            _parametersEditor = new ParametersEditor(sample, state.AvailableDiskPrototypes);
            ParametersEditorContainer.AddChild(_parametersEditor);

            // Both editors because they intertwined
            _diskParameters = new DiskParameters(sample);
            DiskParametersContainer.AddChild(_diskParameters);
            _parametersEditor.OnDisksChanged += () => _diskParameters.UpdateDiskModifiers(_parametersEditor.SelectedDisks);
            _diskParameters.UpdateDiskModifiers(sample.SelectedDiskPrototypes);
        }
        else
        {
            _parametersEditor.UpdateDisks(sample, state.AvailableDiskPrototypes);
            _diskParameters.UpdateDiskModifiers(sample.SelectedDiskPrototypes);
        }

        if (!ProfileEditorContainer.Visible && !ParametersEditorContainer.Visible)
        {
            ShowProfileEditor();
        }

        UpdatePreview(sample.StoredProfile);
    }

    private void ShowProfileEditor()
    {
        ProfileEditorContainer.Visible = true;
        ParametersEditorContainer.Visible = false;
    }

    private void ShowParametersEditor()
    {
        ProfileEditorContainer.Visible = false;
        ParametersEditorContainer.Visible = true;
    }

    /// <summary>
    /// Spawns a dummy client-side entity to visualize the character profile
    /// </summary>
    private void UpdatePreview(HumanoidCharacterProfile? profile)
    {
        if (profile == null)
        {
            ClearPreview();
            return;
        }

        // Spawn dummy or reuse it
        if (_previewDummy == null || !_entityManager.EntityExists(_previewDummy.Value))
        {
            var speciesProto = _prototypeManager.Index(profile.Species);
            _previewDummy = _entityManager.SpawnEntity(speciesProto.DollPrototype, MapCoordinates.Nullspace);

            _spriteView = new SpriteView
            {
                OverrideDirection = Direction.South,
                Scale = new Vector2(4f, 4f),
                MaxSize = new Vector2(256, 256),
                Stretch = SpriteView.StretchMode.Fill,
                HorizontalExpand = true,
                VerticalExpand = true
            };

            CreatureImageContainer.RemoveAllChildren();
            CreatureImageContainer.AddChild(_spriteView);
        }

        _spriteView?.SetEntity(_previewDummy.Value);

        // Apply profile appearance to the dummy entity
        var humanoidSystem = _entityManager.System<HumanoidAppearanceSystem>();
        humanoidSystem.LoadProfile(_previewDummy.Value, profile);
    }

    /// <summary>
    /// Cleans up the preview entity to free resources
    /// </summary>
    private void ClearPreview()
    {
        if (_previewDummy != null && _entityManager.EntityExists(_previewDummy.Value))
        {
            _entityManager.DeleteEntity(_previewDummy.Value);
            _previewDummy = null;
        }
        CreatureImageContainer.RemoveAllChildren();
        _spriteView = null;
    }
}
