using System.Linq;
using Robust.Shared.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Client.UserInterface.Controls;
using Content.Shared._Horizon.Cytology.Components;

namespace Content.Client._Horizon.Cytology.Console.UI;

[GenerateTypedNameReferences]
public sealed partial class DiskParameters : Control
{

    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;
    [Dependency] private readonly IEntityManager _entityManager = default!;

    public DiskParameters(CellSample sample)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    /// <summary>
    /// Refreshes the UI to show the combined effects of all selected disks
    /// Called when the user selects or deselects a disk in the ParametersEditor
    /// </summary>
    /// <param name="selectedDiskPrototypes">List of currently selected disk prototype IDs</param>
    public void UpdateDiskModifiers(List<string>? selectedDiskPrototypes)
    {
        DiskModifiersContainer.DisposeAllChildren();

        if (selectedDiskPrototypes == null || !selectedDiskPrototypes.Any())
        {
            NoModLabel.Visible = true;
            return;
        }
        NoModLabel.Visible = false;

        // Combine modifiers from all selected disks
        var combinedModifiers = CombineDiskModifiers(selectedDiskPrototypes);

        foreach (var (componentType, modifier) in combinedModifiers)
        {
            var modifierLabel = CreateModifierLabel(componentType, modifier);
            DiskModifiersContainer.AddChild(modifierLabel);
        }

    }

    /// <summary>
    /// Aggregates modifiers from multiple disks into a single set of stats
    /// Multiplies percentage modifiers and adds fixed values
    /// </summary>
    private Dictionary<string, CombinedModifier> CombineDiskModifiers(List<string> selectedDiskPrototypes)
    {
        var combined = new Dictionary<string, CombinedModifier>();

        foreach (var protoId in selectedDiskPrototypes)
        {
            // We take protorype then get IComp from this and finaly CytologyDiskComponent
            if (!_prototypeManager.TryIndex<EntityPrototype>(protoId, out var diskProto) ||
                !diskProto.Components.TryGetComponent("CytologyDisk", out var diskC) ||
                diskC is not CytologyDiskComponent diskComp) // ... °˖✧◝(⁰▿⁰)◜✧˖° 
                continue;

            foreach (var modifier in diskComp.Modifiers)
            {
                if (!combined.TryGetValue(modifier.ComponentType, out var existing))
                {
                    combined[modifier.ComponentType] = new CombinedModifier
                    {
                        ComponentType = modifier.ComponentType,
                        PercentModifier = modifier.PercentModifier ?? 1f
                    };
                }
                else
                {
                    if (modifier.PercentModifier.HasValue)
                        existing.PercentModifier *= modifier.PercentModifier.Value;
                }
            }
        }

        return combined;
    }

    private Label CreateModifierLabel(string componentType, CombinedModifier modifier)
    {
        var text = GetModifierDisplayText(componentType, modifier);
        return new Label
        {
            Text = text,
            HorizontalExpand = true,
            Margin = new Thickness(0, 2, 0, 2)
        };
    }

    /// <summary>
    /// Formats the numeric modifier value into a user-friendly string (e.g.,"x1.5")
    /// </summary>
    private string GetModifierDisplayText(string componentType, CombinedModifier modifier)
    {
        var componentName = GetComponentDisplayName(componentType);

        return modifier.PercentModifier != 1f ? $"{componentName}: x{modifier.PercentModifier:F2}" : $"{componentName}: 1"; //TODO проверить
    }

    /// <summary>
    /// Maps internal component type names (e.g., "MobHealth") to localized readable names
    /// </summary>
    private string GetComponentDisplayName(string componentType)
    {
        return componentType switch
        {
            "MobHealth" => Loc.GetString("cytology-console-modifier-health"),
            "MovementSpeedModifier" => Loc.GetString("cytology-console-modifier-speed"),
            "MeleeWeaponDamage" => Loc.GetString("cytology-console-modifier-damage"),
            "HungerRate" => Loc.GetString("cytology-console-modifier-hunger"),
            "Stamina" => Loc.GetString("cytology-console-modifier-stamina"),
            "MaxPlasma" => Loc.GetString("cytology-console-modifier-max-plasma"),
            "PlasmaRechargeSpeed" => Loc.GetString("cytology-console-modifier-plasma-recharge-speed"),
            "GunFireRate" => Loc.GetString("cytology-console-modifier-gun-fire-rate"),
            _ => componentType
        };
    }

    /// <summary>
    /// Helper class to store aggregated stats during calculation
    /// It's kind of a vestige of what I wanted to do. It should be deleted 
    /// </summary>
    private sealed class CombinedModifier
    {
        public string ComponentType = string.Empty;
        public float PercentModifier = 1f;
    }
}
