using Content.Client._Horizon.Cytology.Console.UI.Items;
using Content.Shared._Horizon.Cytology.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using System.Linq;

namespace Content.Client._Horizon.Cytology.Console.UI;

[GenerateTypedNameReferences]
public sealed partial class ParametersEditor : Control
{
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;
    [Dependency] private readonly IEntitySystemManager _entitySystem = default!;

    public const int MaxDisksPerSample = 3;

    private readonly SpriteSystem _spriteSystem = default!;

    private CellSample _cellSample = new CellSample();
    private List<string>? _availableDiskPrototypes;
    private HashSet<string> _selectedDiskPrototypes = new();

    public List<string> SelectedDisks => _selectedDiskPrototypes.ToList();

    public event Action? OnDisksChanged;

    public ParametersEditor(CellSample sample, List<string>? availableDiskPrototypes = null)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _spriteSystem = _entitySystem.GetEntitySystem<SpriteSystem>();

        InitData(sample, availableDiskPrototypes);
    }

    public void UpdateDisks(CellSample sample, List<string>? availableDiskPrototypes)
    {
        InitData(sample, availableDiskPrototypes);
    }

    private void InitData(CellSample sample, List<string>? availableDiskPrototypes)
    {
        _cellSample = sample;
        _availableDiskPrototypes = availableDiskPrototypes;

        _selectedDiskPrototypes.Clear();
        if (sample.SelectedDiskPrototypes != null)
        {
            _selectedDiskPrototypes = new HashSet<string>(sample.SelectedDiskPrototypes);
        }

        InitializeDisks();
        UpdateDiskButtons();
    }

    private void InitializeDisks()
    {
        DisksList.DisposeAllChildren();

        if (_availableDiskPrototypes == null)
            return;

        for (var i = 0; i < _availableDiskPrototypes.Count; i++)
        {
            var protoId = _availableDiskPrototypes[i];
            var isSelected = _selectedDiskPrototypes.Contains(protoId);

            var proto = _prototypeManager.Index<EntityPrototype>(protoId);
            var name = proto.Name;
            var desc = proto.Description;
            var texture = _spriteSystem.Frame0(proto);

            var button = new DiskItem(protoId, name, desc, isSelected, texture);

            button.OnPressed += _ =>
            {
                if (_selectedDiskPrototypes.Contains(protoId))
                {
                    _selectedDiskPrototypes.Remove(protoId);
                    button.Selected = false;
                }
                else
                {
                    // Check if we can add this disk
                    if (!CanAddDisk(protoId))
                    {
                        return;
                    }

                    _selectedDiskPrototypes.Add(protoId);
                    button.Selected = true;
                }

                // Update all buttons to reflect current state
                UpdateDiskButtons();
                OnDisksChanged?.Invoke();
            };

            DisksList.AddChild(button);
        }
    }

    private bool CanAddDisk(string protoId)
    {
        if (_selectedDiskPrototypes.Count >= MaxDisksPerSample)
            return false;

        if (_selectedDiskPrototypes.Contains(protoId))
            return false;
        return true;
    }

    private void UpdateDiskButtons()
    {
        foreach (var child in DisksList.Children)
        {
            if (child is DiskItem diskItem)
            {
                var protoId = diskItem.DiskPrototypeId;
                var isSelected = diskItem.Selected;
                diskItem.Selected = isSelected;

                // Disable button if we can't add this disk
                if (!isSelected)
                {
                    diskItem.Disabled = !CanAddDisk(protoId);
                }
                else
                {
                    diskItem.Disabled = false;
                }
            }
        }
    }
}
