using Content.Client._Horizon.Cytology.Console.UI.Helpers;
using Content.Client.Humanoid;
using Content.Shared._Horizon.Cytology.Components;
using Content.Shared.Humanoid;
using Content.Shared.Humanoid.Markings;
using Content.Shared.Humanoid.Prototypes;
using Content.Shared.Preferences;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Enums;
using Robust.Shared.Prototypes;
using System.Linq;

namespace Content.Client._Horizon.Cytology.Console.UI;

[GenerateTypedNameReferences]
public sealed partial class ProfileEditor : Control
{
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;
    [Dependency] private readonly MarkingManager _markingManager = default!;

    private HumanoidCharacterProfile? _currentProfile;
    private Color? _skinColor;
    private bool _hairVisible = true; // Toggle state for Hair vs FacialHair picker

    private ColorSelectorSliders? _skinColorSelector;
    private ColorSelectorSliders? _eyesColorSelector;

    // Public accessor for parent window to get modified profile
    public HumanoidCharacterProfile? Profile => _currentProfile;

    /// <summary>
    /// It is called at any local profile change (for preview, without sending to the server)
    /// </summary>
    public event Action<HumanoidCharacterProfile?>? OnPreviewChanged;

    /// <summary>
    /// It is called only when you click Save (to send the result to the server)
    /// </summary>
    public event Action<HumanoidCharacterProfile?>? OnProfileChanged;

    public ProfileEditor(CellSample sample)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _currentProfile = sample.StoredProfile;

        InitializeUI();
        UpdateSample(sample);
    }

    #region Initialization

    /// <summary>
    /// Sets up the initial UI structure and event listeners
    /// Called once during constructor
    /// </summary>
    private void InitializeUI()
    {
        InitializeSex();
        InitializeEyesColor();
        InitializeMarkings();
        InitializeHairButtons();

        // Button to toggle between Main Profile Editor and detailed Markings Editor
        MarkingSwitchButton.OnPressed += _ =>
        {
            ProfileBox.Visible = !ProfileBox.Visible;
            MarkingBox.Visible = !MarkingBox.Visible;
        };

        if (_currentProfile != null)
        {
            LoadProfile(_currentProfile);
        }
    }

    private void InitializeSex()
    {
        SexButton.Clear();
        SexButton.AddItem(Loc.GetString("humanoid-profile-editor-sex-male-text"), (int)Sex.Male);
        SexButton.AddItem(Loc.GetString("humanoid-profile-editor-sex-female-text"), (int)Sex.Female);
        SexButton.AddItem(Loc.GetString("humanoid-profile-editor-sex-unsexed-text"), (int)Sex.Unsexed);

        SexButton.OnItemSelected += args =>
        {
            SexButton.SelectId(args.Id);
            SetSex((Sex)args.Id);
        };
    }

    private void InitializeEyesColor()
    {
        _eyesColorSelector = new ColorSelectorSliders
        {
            HorizontalExpand = true
        };
        _eyesColorSelector.OnColorChanged += _ => UpdateEyeColor();
        EyeColorContainer.AddChild(_eyesColorSelector);
    }

    private void InitializeMarkings()
    {
        // Bind all marking events to a single handler that updates the profile
        Markings.OnMarkingAdded += HandleMarkingChange;
        Markings.OnMarkingRemoved += HandleMarkingChange;
        Markings.OnMarkingColorChange += HandleMarkingChange;
        Markings.OnMarkingRankChange += HandleMarkingChange;
    }

    private void InitializeHairButtons()
    {
        // Toggle which picker is visible: Hair or Facial Hair
        HairButton.OnPressed += _ => SetPicker(true);
        FacialHairButton.OnPressed += _ => SetPicker(false);
    }

    #endregion

    #region Profile Loading

    /// <summary>
    /// Updates the editor with a new sample. Called when selecting a different sample in the list
    /// </summary>
    public void UpdateSample(CellSample sample)
    {
        _currentProfile = sample.StoredProfile;

        MarkingSwitchButton.Disabled = _currentProfile == null;

        if (_currentProfile != null)
        {
            LoadProfile(_currentProfile);
        }
        else
        {
            // Show placeholder for creatures without profile
            NoProfileLabel.Visible = true;
            ProfileContainer.Visible = false;
        }
    }

    /// <summary>
    /// Populates all UI fields with data from the provided profile
    /// </summary>
    private void LoadProfile(HumanoidCharacterProfile profile)
    {
        NoProfileLabel.Visible = false;
        ProfileContainer.Visible = true;

        LoadBasicInfo(profile);
        LoadSkinColor(profile);
        LoadEyesColor(profile);
        LoadHairPickers(profile);
        LoadMarkings(profile);

        NotifyPreviewChanged();
    }

    private void LoadBasicInfo(HumanoidCharacterProfile profile)
    {
        NameEdit.Text = profile.Name;
        NameEdit.OnTextChanged += args => UpdateName(args.Text);

        SexButton.SelectId((int)profile.Sex);
    }

    /// <summary>
    /// Determines which skin color control to show (Slider or Color Picker) 
    /// based on the species' skin coloration type
    /// </summary>
    private void LoadSkinColor(HumanoidCharacterProfile profile)
    {
        if (_skinColorSelector == null)
        {
            _skinColorSelector = new ColorSelectorSliders
            {
                HorizontalExpand = true
            };
            _skinColorSelector.OnColorChanged += _ => UpdateSkinColor();
            SkinSlider.OnValueChanged += _ => UpdateSkinColor();
            SkinColorContainer.AddChild(_skinColorSelector);
        }

        var skin = _prototypeManager.Index<SpeciesPrototype>(profile.Species).SkinColoration;

        switch (skin)
        {
            case HumanoidSkinColor.HumanToned:
                SkinSlider.Value = SkinColor.HumanSkinToneFromColor(profile.Appearance.SkinColor);
                SkinSlider.Visible = true;
                SkinColorContainer.Visible = false;
                break;
            case HumanoidSkinColor.KatunianToned:
                SkinSlider.Value = SkinColor.KatunianSkinFromColor(profile.Appearance.SkinColor);
                SkinSlider.Visible = true;
                SkinColorContainer.Visible = false;
                break;
            case HumanoidSkinColor.ShelegToned:
                SkinSlider.Value = SkinColor.ShelegSkinToneFromColor(profile.Appearance.SkinColor);
                SkinSlider.Visible = true;
                SkinColorContainer.Visible = false;
                break;
            default:
                _skinColorSelector.Color = profile.Appearance.SkinColor;
                SkinSlider.Visible = false;
                SkinColorContainer.Visible = true;
                break;
        }
    }

    private void LoadEyesColor(HumanoidCharacterProfile profile)
    {
        if (_eyesColorSelector != null)
        {
            _eyesColorSelector.Color = profile.Appearance.EyeColor;
        }
    }

    private void LoadMarkings(HumanoidCharacterProfile profile)
    {
        Markings.SetData(
            profile.Appearance.Markings,
            profile.Species,
            profile.Sex,
            profile.Appearance.SkinColor,
            profile.Appearance.EyeColor
        );

        UpdateMarkingsColors(profile);
    }

    #endregion

    #region Profile Updates

    private void UpdateName(string newName)
    {
        if (_currentProfile == null)
            return;

        _currentProfile = _currentProfile.WithName(newName);
        NotifyPreviewChanged();
    }

    private void SetSex(Sex newSex)
    {
        if (_currentProfile == null)
            return;

        _currentProfile = _currentProfile.WithSex(newSex);

        // For convenience, default to most common gender when new sex is selected
        var newGender = newSex switch
        {
            Sex.Male => Gender.Male,
            Sex.Female => Gender.Female,
            _ => Gender.Epicene
        };

        _currentProfile = _currentProfile.WithGender(newGender);
        Markings.SetSex(newSex);
        NotifyPreviewChanged();
    }

    private void UpdateEyeColor()
    {
        if (_currentProfile == null || _eyesColorSelector == null)
            return;

        _currentProfile = _currentProfile.WithCharacterAppearance(
            _currentProfile.Appearance.WithEyeColor(_eyesColorSelector.Color)
        );

        Markings.CurrentEyeColor = _eyesColorSelector.Color;
        NotifyPreviewChanged();
    }

    /// <summary>
    /// Calculates the new skin color based on the active control (Slider or RGB Picker)
    /// and applies it to the profile
    /// </summary>
    private void UpdateSkinColor()
    {
        if (_currentProfile == null || _skinColorSelector == null)
            return;

        var skinType = _prototypeManager.Index<SpeciesPrototype>(_currentProfile.Species).SkinColoration;
        var color = CytologySkinUtils.GetSkinColor(skinType, SkinSlider.Value, _skinColorSelector.Color);

        _skinColor = color;
        Markings.CurrentSkinColor = color;
        _currentProfile = _currentProfile.WithCharacterAppearance(
            _currentProfile.Appearance.WithSkinColor(color)
        );

        UpdateSkinColorAndMarkings(color);
        Markings.CurrentSkinColor = color;
        UpdateMarkingsHairAndFacialHair();
        NotifyPreviewChanged();
    }

    /// <summary>
    /// Ensures that hair and facial hair match the skin color for specific species (e.g. slime)
    /// </summary>
    private void UpdateSkinColorAndMarkings(Color color)
    {
        if (_currentProfile == null)
            return;

        var appearance = _currentProfile.Appearance;

        var newHairColor = appearance.HairColor;
        if (_markingManager.MustMatchSkin(_currentProfile.Species, HumanoidVisualLayers.Hair, out _, _prototypeManager))
            newHairColor = color;

        var newFacialHairColor = appearance.FacialHairColor;
        if (_markingManager.MustMatchSkin(_currentProfile.Species, HumanoidVisualLayers.FacialHair, out _, _prototypeManager))
            newFacialHairColor = color;

        _currentProfile = _currentProfile.WithCharacterAppearance(
            appearance.WithSkinColor(color)
                      .WithHairColor(newHairColor)
                      .WithFacialHairColor(newFacialHairColor)
        );
    }

    private void HandleMarkingChange(MarkingSet markings)
    {
        if (_currentProfile == null)
            return;

        _currentProfile = _currentProfile.WithCharacterAppearance(
            _currentProfile.Appearance.WithMarkings(markings.GetForwardEnumerator().ToList())
        );
        NotifyPreviewChanged();
    }

    #endregion

    #region Markings

    /// <summary>
    /// Synchronizes the markings editor context with the current profile state
    /// </summary>
    private void UpdateMarkingsColors(HumanoidCharacterProfile profile)
    {
        Markings.CurrentSkinColor = profile.Appearance.SkinColor;
        Markings.CurrentEyeColor = profile.Appearance.EyeColor;
        UpdateMarkingsHairAndFacialHair();
    }

    private void UpdateMarkingsHairAndFacialHair()
    {
        if (_currentProfile == null)
            return;

        UpdateMarkingsHair();
        UpdateMarkingsFacialHair();
    }

    private void UpdateMarkingsHair() // TODO тут надо поправить
    {
        if (_currentProfile == null)
            return;

        Color? hairColor = null;
        if (_currentProfile.Appearance.HairStyleId != HairStyles.DefaultHairStyle &&
            _markingManager.Markings.TryGetValue(_currentProfile.Appearance.HairStyleId, out var hairProto))
        {
            if (_markingManager.CanBeApplied(_currentProfile.Species, _currentProfile.Sex, hairProto, _prototypeManager))
            {
                hairColor = _markingManager.MustMatchSkin(_currentProfile.Species, HumanoidVisualLayers.Hair, out _, _prototypeManager)
                    ? _currentProfile.Appearance.SkinColor
                    : _currentProfile.Appearance.HairColor;
            }
        }

        Markings.HairMarking = hairColor != null
            ? new Marking(_currentProfile.Appearance.HairStyleId, new List<Color> { hairColor.Value })
            : null;
    }

    private void UpdateMarkingsFacialHair()
    {
        if (_currentProfile == null)
            return;

        Color? facialHairColor = null;
        if (_currentProfile.Appearance.FacialHairStyleId != HairStyles.DefaultFacialHairStyle &&
            _markingManager.Markings.TryGetValue(_currentProfile.Appearance.FacialHairStyleId, out var facialHairProto))
        {
            if (_markingManager.CanBeApplied(_currentProfile.Species, _currentProfile.Sex, facialHairProto, _prototypeManager))
            {
                facialHairColor = _markingManager.MustMatchSkin(_currentProfile.Species, HumanoidVisualLayers.FacialHair, out _, _prototypeManager)
                    ? _currentProfile.Appearance.SkinColor
                    : _currentProfile.Appearance.FacialHairColor;
            }
        }

        Markings.FacialHairMarking = facialHairColor != null
            ? new Marking(_currentProfile.Appearance.FacialHairStyleId, new List<Color> { facialHairColor.Value })
            : null;
    }

    #endregion

    #region Hair/Facial Hair

    /// <summary>
    /// Toggles visibility between Hair Picker and Facial Hair Picker
    /// </summary>
    /// <param name="hair">If true, shows Hair picker. If false, shows Facial Hair picker</param>
    private void SetPicker(bool showHair)
    {
        _hairVisible = showHair;
        FacialHairPicker.Visible = !_hairVisible;
        HairPicker.Visible = _hairVisible;
    }

    private void LoadHairPickers(HumanoidCharacterProfile profile)
    {
        var markingSet = BuildMarkingSet(profile);

        var hair = markingSet.TryGetCategory(MarkingCategories.Hair, out var hairMarkings)
            ? new List<Marking>(hairMarkings)
            : new List<Marking>();

        var facialHair = markingSet.TryGetCategory(MarkingCategories.FacialHair, out var facialHairMarkings)
            ? new List<Marking>(facialHairMarkings)
            : new List<Marking>();

        // Convert HairStyleId/FacialHairStyleId to Marking list if needed
        if (hair.Count == 0 && profile.Appearance.HairStyleId != HairStyles.DefaultHairStyle)
            hair = new List<Marking> { new(profile.Appearance.HairStyleId, new List<Color> { profile.Appearance.HairColor }) };

        if (facialHair.Count == 0 && profile.Appearance.FacialHairStyleId != HairStyles.DefaultFacialHairStyle)
            facialHair = new List<Marking> { new(profile.Appearance.FacialHairStyleId, new List<Color> { profile.Appearance.FacialHairColor }) };

        HairPicker.UpdateData(hair, profile.Species, markingSet.PointsLeft(MarkingCategories.Hair) + hair.Count);
        var hasHair = profile.Appearance.HairStyleId != HairStyles.DefaultHairStyle;
        UpdateHairPickerButtons(HairPicker, hasHair);
        HairPicker.Visible = _hairVisible;

        FacialHairPicker.UpdateData(facialHair, profile.Species, markingSet.PointsLeft(MarkingCategories.FacialHair) + facialHair.Count);
        var hasFacialHair = profile.Appearance.FacialHairStyleId != HairStyles.DefaultFacialHairStyle;
        UpdateHairPickerButtons(FacialHairPicker, hasFacialHair);
        FacialHairPicker.Visible = !_hairVisible;

        ConfigureHairPicker();
        ConfigureFacialHairPicker();
    }

    /// <summary>
    /// Here we are changing the built-in container to make it more suitable for the window design 
    /// </summary>
    private void UpdateHairPickerButtons(SingleMarkingPicker picker, bool hasMarking)
    {
        foreach (var pickerChild in picker.Children)
        {
            if (pickerChild is BoxContainer container && container.Name == "SlotSelectorContainer")
            {
                foreach (var child in container.Children)
                {
                    if (child is BaseButton addButton && addButton.Name == "AddButton")
                    {
                        addButton.Visible = !hasMarking;
                    }
                    else if (child is BaseButton removeButton && removeButton.Name == "RemoveButton")
                    {
                        removeButton.Visible = hasMarking;
                        removeButton.HorizontalExpand = true;
                    }
                    else if (child is Control slotSelector && slotSelector.Name == "SlotSelector")
                    {
                        slotSelector.Visible = false;
                    }
                }
            }
        }
    }

    private void ConfigureHairPicker()
    {
        HairPicker.OnMarkingSelect = args =>
        {
            if (_currentProfile == null)
                return;

            var markingId = args.id;

            _currentProfile = _currentProfile.WithCharacterAppearance(
                _currentProfile.Appearance.WithHairStyleName(markingId)
                    .WithHairColor(_currentProfile.Appearance.HairColor) // TODO быть может, от этого можно избавиться вовсе
            );

            UpdateHairPickerButtons(HairPicker, markingId != HairStyles.DefaultHairStyle);
            UpdateMarkingsHair();
            NotifyPreviewChanged();
        };

        HairPicker.OnColorChanged = args =>
        {
            if (_currentProfile == null)
                return;

            var color = args.marking.MarkingColors.Count > 0 ? args.marking.MarkingColors[0] : Color.Black;
            _currentProfile = _currentProfile.WithCharacterAppearance(
                _currentProfile.Appearance.WithHairColor(color)
            );

            UpdateMarkingsHair();
            NotifyPreviewChanged();
        };

        HairPicker.OnSlotAdd = () =>
        {
            if (_currentProfile == null)
                return;

            var defaultHair = _markingManager.MarkingsByCategoryAndSpecies(MarkingCategories.Hair, _currentProfile.Species).Keys
                .FirstOrDefault();

            if (!string.IsNullOrEmpty(defaultHair))
            {
                _currentProfile = _currentProfile.WithCharacterAppearance(
                    _currentProfile.Appearance.WithHairStyleName(defaultHair)
                );

                UpdateHairPickerButtons(HairPicker, true);
                LoadHairPickers(_currentProfile);
                UpdateMarkingsHair();
                NotifyPreviewChanged();
            }
        };

        HairPicker.OnSlotRemove = _ =>
        {
            if (_currentProfile == null)
                return;

            _currentProfile = _currentProfile.WithCharacterAppearance(
                _currentProfile.Appearance.WithHairStyleName(HairStyles.DefaultHairStyle)
            );

            UpdateHairPickerButtons(HairPicker, false);
            LoadHairPickers(_currentProfile);
            UpdateMarkingsHair();
            NotifyPreviewChanged();
        };
    }

    private void ConfigureFacialHairPicker()
    {
        FacialHairPicker.OnMarkingSelect = args =>
        {
            if (_currentProfile == null)
                return;

            var markingId = args.id;

            _currentProfile = _currentProfile.WithCharacterAppearance(
                _currentProfile.Appearance.WithFacialHairStyleName(markingId)
                    .WithFacialHairColor(_currentProfile.Appearance.FacialHairColor) // TODO быть может, от этого можно избавиться вовсе
            );

            UpdateHairPickerButtons(FacialHairPicker, markingId != HairStyles.DefaultFacialHairStyle);
            UpdateMarkingsFacialHair();
            NotifyPreviewChanged();
        };

        FacialHairPicker.OnColorChanged = args =>
        {
            if (_currentProfile == null)
                return;

            var color = args.marking.MarkingColors.Count > 0 ? args.marking.MarkingColors[0] : Color.Black;
            _currentProfile = _currentProfile.WithCharacterAppearance(
                _currentProfile.Appearance.WithFacialHairColor(color)
            );

            UpdateMarkingsFacialHair();
            NotifyPreviewChanged();
        };

        FacialHairPicker.OnSlotAdd = () =>
        {
            if (_currentProfile == null)
                return;

            var defaultFacialHair = _markingManager.MarkingsByCategoryAndSpecies(MarkingCategories.FacialHair, _currentProfile.Species).Keys
                .FirstOrDefault();

            if (!string.IsNullOrEmpty(defaultFacialHair))
            {
                _currentProfile = _currentProfile.WithCharacterAppearance(
                    _currentProfile.Appearance.WithFacialHairStyleName(defaultFacialHair)
                );

                UpdateHairPickerButtons(FacialHairPicker, true);
                LoadHairPickers(_currentProfile);
                UpdateMarkingsFacialHair();
                NotifyPreviewChanged();
            }
        };

        FacialHairPicker.OnSlotRemove = _ =>
        {
            if (_currentProfile == null)
                return;

            _currentProfile = _currentProfile.WithCharacterAppearance(
                _currentProfile.Appearance.WithFacialHairStyleName(HairStyles.DefaultFacialHairStyle)
            );

            UpdateHairPickerButtons(FacialHairPicker, false);
            LoadHairPickers(_currentProfile);
            UpdateMarkingsFacialHair();
            NotifyPreviewChanged();
        };
    }

    private MarkingSet BuildMarkingSet(HumanoidCharacterProfile profile)
    {
        var species = profile.Species;
        var speciesProto = _prototypeManager.Index<SpeciesPrototype>(species);
        var pointsPrototype = speciesProto.MarkingPoints;

        var set = new MarkingSet(profile.Appearance.Markings, pointsPrototype);
        set.EnsureSpecies(species, profile.Appearance.SkinColor);

        return set;
    }

    #endregion

    #region Preview

    public void UpdatePreviewFromProfile()
    {
        NotifyPreviewChanged();
    }

    /// <summary>
    /// Helper to safely invoke the preview change event with the current profile
    /// </summary>
    private void NotifyPreviewChanged()
    {
        if (_currentProfile != null)
        {
            OnPreviewChanged?.Invoke(_currentProfile);
        }
    }

    #endregion
}
