using System.Linq;
using Content.Client.Message;
using Content.Shared._Horizon.Sponsors;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.Player;
using Robust.Shared.Utility;

namespace Content.Client._Horizon.Sponsors.UI;

[GenerateTypedNameReferences]
public sealed partial class SponsorShopMenu : DefaultWindow
{
    [Dependency] private readonly SponsorShopUIController _uiController = default!;
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;
    [Dependency] private readonly IPlayerManager _playerManager = default!;
    [Dependency] private readonly IEntityManager _entityManager = default!;

    public string CurrentCategory { get; set; } = string.Empty;
    private string _searchText = string.Empty;

    public SponsorShopMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        SearchBox.OnTextChanged += SearchBox_OnTextChanged;
        ClearButton.OnPressed += ClearButton_OnPressed;

        UpdateBalance(0);
        PopulateCategories();
    }

    public void UpdateBalance(int balance)
    {
        BalanceInfo.SetMarkup($"Баланс: {balance}");
    }

    private void PopulateCategories()
    {
        var allCategories = _prototypeManager.EnumeratePrototypes<SponsorShopCategoryPrototype>()
            .OrderBy(p => p.Priority)
            .ToList();

        // Разделяем на родительские категории и подкатегории
        var parentCategories = allCategories.Where(p => p.Parent == null).ToList();
        var childCategories = allCategories.Where(p => p.Parent != null).ToList();

        var group = new ButtonGroup();
        string? firstCategoryId = null;

        foreach (var parentProto in parentCategories)
        {
            // Получаем подкатегории для этой родительской категории
            var children = childCategories
                .Where(c => c.Parent == parentProto.ID)
                .OrderBy(c => c.Priority)
                .ToList();

            if (children.Count > 0)
            {
                // Создаём Collapsible с подкатегориями
                var collapsible = new Collapsible();
                var heading = new CollapsibleHeading(Loc.GetString(parentProto.Name));
                var body = new CollapsibleBody();

                // BoxContainer для вертикального расположения кнопок
                var buttonsContainer = new BoxContainer
                {
                    Orientation = BoxContainer.LayoutOrientation.Vertical
                };

                foreach (var childProto in children)
                {
                    var catButton = new Button
                    {
                        Text = Loc.GetString(childProto.Name),
                        ToggleMode = true,
                        Group = group,
                        StyleClasses = { "OpenBoth" }
                    };
                    catButton.OnPressed += _ => SetCategory(childProto.ID);
                    buttonsContainer.AddChild(catButton);

                    firstCategoryId ??= childProto.ID;
                }

                body.AddChild(buttonsContainer);
                collapsible.AddChild(heading);
                collapsible.AddChild(body);
                CategoryListContainer.AddChild(collapsible);
            }
            else if (parentProto.Items.Count > 0)
            {
                // Категория без детей, но с предметами - показываем как обычную кнопку
                var catButton = new Button
                {
                    Text = Loc.GetString(parentProto.Name),
                    ToggleMode = true,
                    Group = group,
                    StyleClasses = { "OpenBoth" }
                };
                catButton.OnPressed += _ => SetCategory(parentProto.ID);
                CategoryListContainer.AddChild(catButton);

                firstCategoryId ??= parentProto.ID;
            }
            // Пустые категории-разделители без детей и без items не добавляем
        }

        if (firstCategoryId != null)
        {
            SetCategory(firstCategoryId);
        }
    }

    private void SetCategory(string categoryId)
    {
        CurrentCategory = categoryId;
        UpdateListings();
    }

    private void SearchBox_OnTextChanged(LineEdit.LineEditEventArgs args)
    {
        _searchText = args.Text;
        ClearButton.Disabled = string.IsNullOrEmpty(_searchText);
        UpdateListings();
    }

    private void ClearButton_OnPressed(BaseButton.ButtonEventArgs args)
    {
        SearchBox.Clear();
        _searchText = string.Empty;
        ClearButton.Disabled = true;
        UpdateListings();
    }

    public void UpdateListings()
    {
        SponsorShopListingsContainer.Children.Clear();

        var categoryPrototype = _prototypeManager.EnumeratePrototypes<SponsorShopCategoryPrototype>()
            .FirstOrDefault(p => p.ID == CurrentCategory);

        if (categoryPrototype != null)
        {
            var listings = categoryPrototype.Items
                .Select(id => _prototypeManager.Index<SponsorShopListingPrototype>(id))
                .Where(p => p.Name.Contains(_searchText, StringComparison.OrdinalIgnoreCase))
                .ToList();

            foreach (var listing in listings)
            {
                AddListingGui(listing);
            }
        }
    }

    private void AddListingGui(SponsorShopListingPrototype listing)
    {
        var spriteSys = _entityManager.EntitySysManager.GetEntitySystem<SpriteSystem>();

        Texture? texture = null;

        var componentFactory = IoCManager.Resolve<IComponentFactory>();

        if (_prototypeManager.TryIndex<EntityPrototype>(listing.PrototypeId, out var prototype))
        {
            if (prototype.TryGetComponent<SpriteComponent>(out var sprite, componentFactory))
            {
                if (sprite.BaseRSI != null)
                {
                    var icon = new SpriteSpecifier.Rsi(ResPath.FromRelativeSystemPath(sprite.BaseRSI.Path.ToString()), listing.State);
                    texture = spriteSys.Frame0(icon);
                }
            }
        }

        var listingControl = new SponsorShopListingControl(listing, texture);
        listingControl.BuyButton.OnButtonDown += _ => OnBuyButtonPressed(listing);

        SponsorShopListingsContainer.AddChild(listingControl);
    }

    private void OnBuyButtonPressed(SponsorShopListingPrototype listing)
    {
        if (_playerManager.LocalSession == null)
            return;

        var playerName = _playerManager.LocalSession.Name;
        var player = _playerManager.LocalSession.AttachedEntity;

        if (player == null)
            return;

        var netEntity = IoCManager.Resolve<IEntityManager>().GetNetEntity(player.Value);
        _uiController.BuyItem(playerName, listing.Cost, netEntity, listing.PrototypeId);
    }
}
