using Content.Shared._Horizon.Sponsors;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.XAML;
using Robust.Client.UserInterface;

namespace Content.Client._Horizon.Sponsors.UI;

[GenerateTypedNameReferences]
public sealed partial class SponsorShopListingControl : Control
{
    public SponsorShopListingControl(SponsorShopListingPrototype listing, Texture? texture = null)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        ItemName.Text = Loc.GetString(listing.Name);
        ItemDescription.SetMessage(Loc.GetString(listing.Description));

        PriceLabel.Text = $"Цена: {listing.Cost}";

        if (texture != null)
        {
            ItemTexture.Texture = texture;
        }

        BuyButton.Text = "Купить";
    }
}
